# Generated by Django 4.2.3 on 2023-10-10 17:26

from django.db import migrations, models
import news.models.category_validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200,
                        validators=[
                            news.models.category_validators.validate_name_field
                        ],
                    ),
                ),
            ],
        ),
    ]
